; Drupal.org release file.
core = 7.x
api = 2

; Basic contributed modules.
projects[ctools][version] = 1.3
projects[ctools][subdir] = "contrib"
projects[entity][version] = 1.1
projects[entity][subdir] = "contrib"
projects[entityreference][version] = 1.0
projects[entityreference][subdir] = "contrib"
projects[rules][version] = 2.3
projects[rules][subdir] = "contrib"
projects[views][version] = 3.7
projects[views][subdir] = "contrib"
projects[views_bulk_operations][version] = 3.1
projects[views_bulk_operations][subdir] = "contrib"
projects[addressfield][version] = 1.0-beta4
projects[addressfield][subdir] = "contrib"
projects[features][version] = 1.0
projects[features][subdir] = "contrib"
projects[strongarm][version] = 2.0
projects[strongarm][subdir] = "contrib"
projects[taxonomy_menu][version] = 1.4
projects[taxonomy_menu][subdir] = "contrib"
projects[libraries][version] = 2.1
projects[libraries][subdir] = "contrib"
projects[views_megarow][version] = 1.0
projects[views_megarow][subdir] = "contrib"

; Other contribs.
projects[bean][version] = 1.2
projects[bean][subdir] = "contrib"
projects[colorbox][version] = 2.4
projects[colorbox][subdir] = "contrib"
projects[physical][version] = 1.x-dev
projects[physical][subdir] = "contrib"
projects[crumbs][version] = 1.9
projects[crumbs][subdir] = "contrib"
projects[inline_entity_form][version] = 1.2
projects[inline_entity_form][subdir] = "contrib"
projects[field_extractor][version] = 1.3
projects[field_extractor][subdir] = "contrib"
projects[mailsystem][version] = 2.34
projects[mailsystem][subdir] = "contrib"
projects[mimemail][version] = 1.0-alpha2
projects[mimemail][subdir] = "contrib"
projects[mimemail][patch][] = "http://drupal.org/files/1585546-2-move-rules-actions.patch"
projects[token][version] = 1.5
projects[token][subdir] = "contrib"
projects[token][patch][] = "http://drupal.org/files/token-token_asort_tokens-1712336_0.patch"
projects[eva][version] = 1.2
projects[eva][subdir] = "contrib"
projects[message][version] = 1.8
projects[message][subdir] = "contrib"
projects[message][patch][] = "http://drupal.org/files/message-fix-table-index-name-1941448-3.patch"
projects[message_notify][version] = 2.5
projects[message_notify][subdir] = "contrib"
projects[migrate][version] = 2.5
projects[migrate][subdir] = "contrib"
projects[migrate_extras][version] = 2.5
projects[migrate_extras][subdir] = "contrib"
projects[migrate_extras][patch][] = "http://drupal.org/files/migrate_extras-fix-destid2-array-1951904-4.patch"
projects[date][version] = 2.6
projects[date][subdir] = "contrib"
projects[menu_attributes][version] = 1.0-rc2
projects[menu_attributes][subdir] = "contrib"
projects[fences][version] = "1.0"
projects[fences][subdir] = "contrib"
projects[fences][patch][] = "http://drupal.org/files/undefined-index-1561244-7.patch"
projects[fences][patch][] = "http://drupal.org/files/fences-default_markup_option-1857230-2.patch"
projects[title][version] = "1.0-alpha7"
projects[title][subdir] = "contrib"
projects[title][patch][] = "http://drupal.org/files/title-translation_overwrite-1269076-35.patch"

; Search related modules.
projects[search_api][version] = 1.6
projects[search_api][subdir] = "contrib"
projects[search_api_db][version] = 1.0-rc1
projects[search_api_db][subdir] = "contrib"
projects[search_api_ranges][version] = 1.4
projects[search_api_ranges][subdir] = "contrib"
projects[search_api_ranges][patch][] = "http://drupal.org/files/search_api_ranges-rewrite-data-alteration-callback-2001846-3.patch"
projects[facetapi][version] = 1.3
projects[facetapi][subdir] = "contrib"
projects[facetapi][patch][] = "http://drupal.org/files/facetapi-1616518-13-show-active-term.patch"
projects[search_api_sorts][version] = 1.4
projects[search_api_sorts][subdir] = "contrib"

; UI improvement modules.
projects[module_filter][version] = 1.7
projects[module_filter][subdir] = "contrib"
projects[image_delta_formatter][version] = 1.0-rc1
projects[image_delta_formatter][subdir] = "contrib"
projects[link][version] = 1.1
projects[link][subdir] = "contrib"
projects[link][patch][] = "http://drupal.org/files/Fixed_title_value_in_link_field_update_instance_undefined-1914286-3.patch"
projects[link][patch][] = "http://drupal.org/files/link-fix-undefined-index-widget-1918850-9.patch"
projects[pathauto][version] = 1.2
projects[pathauto][subdir] = "contrib"
projects[cloud_zoom][version] = 1.x-dev
projects[cloud_zoom][subdir] = "contrib"
projects[special_menu_items][version] = 2.0
projects[special_menu_items][subdir] = "contrib"
projects[chosen][version] = 1.x-dev
projects[chosen][subdir] = "contrib"

; Base theme.
projects[omega][version] = 3.1
projects[omega_kickstart][version] = 3.3
projects[shiny][version] = 1.2

; Libraries.
libraries[colorbox][type] = "libraries"
libraries[colorbox][download][type] = "file"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox/archive/master.zip"
libraries[chosen][type] = "libraries"
libraries[chosen][download][type] = "file"
libraries[chosen][download][url] = "https://github.com/harvesthq/chosen/archive/master.zip"
libraries[chosen][overwrite] = TRUE
